### ISSUE TITLE
Use more precise JSON encoder

### ISSUE THREAD

**Issue by pydanny** [bipsandbytes/django-api#1]
As you can see in https://github.com/audreyr/standardjson's encoders at https://github.com/audreyr/standardjson/blob/master/standardjson/encoder_funcs.py there are a few edge cases that can cause problems.

**Comment by bipsandbytes** [comment]
Thank you for the report, @pydanny!
I ended up choosing [Django's JSON serializer](https://docs.djangoproject.com/en/1.7/topics/serialization/#serialization-formats-json) which is compatible with ECMA-262.
Here's the relevant commit: https://github.com/bipsandbytes/django-api/commit/6da66ff9fac47f50ddbb737dc56874379f1135cf
